<a href="https://colab.research.google.com/github/RaziehGolzari/Git/blob/main/video_exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d=tf.constant([2,-1,5,8,9],dtype=tf.float32)
print(tensor_one_d )

tf.Tensor([ 2. -1.  5.  8.  9.], shape=(5,), dtype=float32)


In [ ]:
tensor_two_d=tf.constant([
    [2,4,-1],
    [3,10,-9],
    [3,10,-5],
    [1,2,-4]
    ])
print(tensor_two_d)

tf.Tensor(
[[ 2  4 -1]
 [ 3 10 -9]
 [ 3 10 -5]
 [ 1  2 -4]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d=tf.constant([
    [[1,2,3],
     [3,4,5]],
    [[4,5,6],
     [5,6,7]],
    [[6,7,8],
    [7,8,9]],
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]

 [[6 7 8]
  [7 8 9]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(3, 2, 3)


In [ ]:
print(tensor_three_d.ndim)

3


In [ ]:
tensor_four_d = tf.constant([
[
    [[1,2,3],
     [3,4,5]],
    [[4,5,6],
     [5,6,7]],
    [[6,7,8],
    [7,8,9]],],

  [
    [[1,2,3],
     [3,42,5]],
    [[4,5,6],
     [5,16,7]],
    [[96,7,8],
    [7,48,9]],],

 [
    [[1,2,3],
     [3,42,5]],
    [[4,5,6],
     [5,16,7]],
    [[96,7,8],
    [7,48,9]],],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 3  4  5]]

  [[ 4  5  6]
   [ 5  6  7]]

  [[ 6  7  8]
   [ 7  8  9]]]


 [[[ 1  2  3]
   [ 3 42  5]]

  [[ 4  5  6]
   [ 5 16  7]]

  [[96  7  8]
   [ 7 48  9]]]


 [[[ 1  2  3]
   [ 3 42  5]]

  [[ 4  5  6]
   [ 5 16  7]]

  [[96  7  8]
   [ 7 48  9]]]], shape=(3, 3, 2, 3), dtype=int32)


In [ ]:
import numpy as np

In [ ]:
np_array=np.array([1,2,3])
print (np_array)

[1 2 3]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)

In [ ]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
print(eye_tensor*3)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [ ]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [ ]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)
